### ISSUE TITLE
[SOLVED]Loaded module xxx not found in sys.modules

### ISSUE THREAD

**Issue by gr4ph0s** [NiklasRosenstein/localimport#16]
Firstly I would like to thanks you for all your work. And you really push myself to also doing more open source stuff ! :)
I get this message when trying to import my module in a pretty complex environement (even if it's there is nothing fency)

You can look at my project here => https://github.com/gr4ph0s/PoseMaster

I use it with C4D R17, python 2.7.9

Anyway thanks you ! 👍

**Comment by NiklasRosenstein** [comment]
Hey @gr4ph0s , thanks for the kind words. :)

I'll take a closer look another day. For now, I see that you use localimport in every single Python source file. That is not necessary, and potentially the cause of the problem. You only need to use it once in your main Python plugin fail from which you import all your components.

Cheers

**Comment by gr4ph0s** [comment]
Thanks I gonna do some test later on day I will back with result. 
Anyway it's very helpfull class !

**Comment by gr4ph0s** [comment]
Ok. That fixed it. Thanks you alot.
Do you have some papers on import because I'm not sure to understand everything.

**Comment by NiklasRosenstein** [comment]
Great :)
I'm not a good tutorial writer unfortunately. There's some info here in the C4DDev documentation

https://niklasrosenstein.github.io/c4ddev/py4d-imports-howto/

Otherwise, I think you'll find a bunch of information on Google. If you have a specific question, ask way.
